import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const publicDir = join(root, "public");
const publicAssets = join(publicDir, "assets");

rmSync(publicAssets, { recursive: true, force: true });
mkdirSync(publicDir, { recursive: true });
cpSync(join(root, "assets"), publicAssets, { recursive: true });

const html = readFileSync(join(root, "index.html"), "utf8");
writeFileSync(
  join(root, "app", "site-html.ts"),
  `// Generated by prepare-sites.mjs.\nexport const siteHtml = ${JSON.stringify(html)};\n`,
);
